server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route                 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://provider-payment        #提供微服务名进行匹配，带有负载均衡功能
          predicates:                       # 断言，路径相匹配的进行路由
            - Path=/payment/getPaymentById/**

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://provider-payment
          predicates:
            - Path=/payment/lb/**
            #- After=2021-10-02T10:50:47.799+08:00[Asia/Shanghai]
            #- Cookie=username,linwei #带cookie访问
            #- Query=param1,value     #带参数访问
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#          filters:
#            - AddRequestParameter=name,Pay #增加查询参数
#            - AddRequestHeader=X-Request-Red, Blue-{segment} #增加请求头参数
#            - AddResponseHeader=foo, bar-{segment} #增加响应头中参数
#            - RemoveRequestHeader=X-Request-Foo #删除指定的请求头参数
#            - RemoveResponseHeader=X-Response-Foo #删除指定响应头参数
#            - RemoveRequestParameter=red #删除请求参数

        - id: payment_route3
          uri: http://news.baidu.com/guonei
          predicates:
              - Path=/guonei/**

        - id: payment_route4
          uri: http://news.baidu.com/sports
          predicates:
            - Query=sports  #参数
eureka:
  instance:
    instance-id: gateway-service
    hostname: gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
