server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    registerWithEureka: false     #false表示不向注册中心注册自己。
    fetchRegistry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server 交互的地址  查询服务和注册服务都需要依赖此地址
      #集群指向其它eureka
       defaultZone: http://eureka7001.com:7001